services:
  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "3001:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro  # Mount thư mục dist vào Nginx
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount file cấu hình Nginx (tùy chọn)
    restart: unless-stopped